import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ReactFlowProvider } from "@xyflow/react";
import { AuthGuard } from "@/components/AuthGuard";
import { AuthProvider } from "@/components/AuthProvider";
import Header from "@/components/header/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex w-full h-screen overflow-y-hidden">
          <div className="page-wrapper flex w-full">
            {/* <Sidebar /> */}
            <div className="body-wrapper flex flex-col w-full bg-primary">
              {/* <Header layoutType="vertical" /> */}
              {/* <NavBar /> */}
              <main className="flex-1 overflow-hidden">
                <div className="h-full">
                  <AuthProvider>
                    <ReactFlowProvider>
                      <AuthGuard>{children}</AuthGuard>
                    </ReactFlowProvider>
                  </AuthProvider>
                </div>
              </main>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
